local ObbyConfig = {
	ObbyFolderName = "Obby",
	CheckpointName = "CheckPoint",
	DefaultStage = 1,
	KillBrickTag = "KillBrick",
	CheckpointCoolDown = 0.5,
	Level15BadgeId = 1623073761035482,
	CompletionBadgeId = 3158809878982794,
	MainGamePlaceId = 82614076557684,
	SkipStageDevProductId = 0,
	PremiumDanceGamepassId = 1234544490,
	MaxWalkSpeed = 32,
	VoidYThreshold = -150,
	MaxCheckpointTouchDistance = 35,
}

return ObbyConfig
